// <auto-generated />
using System;
using LinkShortener.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LinkShortener.DAL.Migrations
{
    [DbContext(typeof(ShortLinkDbContext))]
    [Migration("20221023221518_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("LinkShortener.DAL.Models.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)");

                    b.Property<int>("CountClick")
                        .HasColumnType("int(11)");

                    b.Property<DateTime>("DateCreate")
                        .HasColumnType("date");

                    b.Property<string>("LongUrl")
                        .IsRequired()
                        .HasColumnType("varchar(10000)");

                    b.Property<string>("ShortUrl")
                        .IsRequired()
                        .HasColumnType("varchar(10000)");

                    b.HasKey("Id");

                    b.ToTable("links");
                });
#pragma warning restore 612, 618
        }
    }
}
